config/routes.rb
Rails.application.routes.draw do
    
  get 'customers/index'
  get 'customers/show'
  get 'customers/edit'
  get 'customers/update'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
  resources :homes, only:[:top]
  resources :customers, only:[:index, :edit, :show, :update]
  resources :items, only:[:index, :new, :creste, :show, :edit, :update]
end
  root "admins/homes#top"
  devise_for :customers
  root 'homes#top'
  get '/about'=> 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :carts, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
  end

  def show
  @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    
  end

end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   def after_sign_out_path_for(resource)
    new_admin_session_path # ログアウト後に遷移するpathを設定(admin側)
   end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/admins/customers/index.html.erb
<h2>会員一覧</h2>
<table class="teble">
  <thead>
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>
        <%= link_to "伊藤 健太郎", "#" %>
      </td>
      <td>hogehogehoge@gmail.com</td>
      <td>有効</td>
    </tr>
  </tbody>
</table>

app/views/admins/customers/show.html.erb
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>

app/views/admins/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/admins/homes/top.html.erb
<h1>管理者画面</h1>
<p>本日の注文件数</p>
<h2>ログアウト</h2>
<%= link_to "ログアウト", destroy_admin_session_path, class: "glyphicon glyphicon-log-out logout", method: :delete %>

app/views/admins/items/create.html.erb
<h1>Admins::Items#create</h1>
<p>Find me in app/views/admins/items/create.html.erb</p>

app/views/admins/items/edit.html.erb
<h1>Admins::Items#edit</h1>
<p>Find me in app/views/admins/items/edit.html.erb</p>

app/views/admins/items/index.html.erb
<div class="row">
  <div class="col-xs-9">
		<h2>商品一覧</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>商品ID</th>
					<th>商品名</th>
					<th>税抜価格</th>
					<th>ジャンル</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
			 <% @items.each do |product| %>
			 <tr>
			   <td><%= item.id %></td>
			   <td><%= link_to admin_item_path(item)%></td>
			   <td></td>
			   <td>ケーキ</td>
			   <td>販売中</td>
			 </tr>
			 <% end %>
			</tbody>
		<% paginate @items%>
</div>

app/views/admins/items/new.html.erb
<div class="row">
  <h2>商品新規登録</h2>
  <%= form_with model:@item, url: admins_items_path, method: :post do |f| %>
  <div class="col-xs-4">
    <%= attachment_image_tag(@item, :image_id, size: "300x300", format: 'jpeg', fallback: "no-image.png") %>
    <%= f.attachment_field :image %>
  </div>
  <div class="col-xs-8">
    <h4>商品名</h4>
      <%= f.text_field :name %>
    <h4>商品説明</h4>
      <%= f.text_field :explanation %>
    <h4>ジャンル</h4>
      <%= f.select :genre_id %>
    <h4>税抜価格</h4>
      <%= f.text_field :price %>
    <h4>販売ステータス</h4>
      <%= f.select :is_status %>
  </div>
  <% end %>
</div>

app/views/admins/items/show.html.erb
<div class="row">
<h2>商品詳細</h2>
  <div class="col-xs-3">
    <%= attachment_image_tag(@item, :image, size: "300x300", format: 'jpeg', fallback: "no-image.png") %>
  </div>
  <div class="col-xs-7">
    <div>
      <h4>商品名　　</h4>
      <span><%= @item.name%></span>
    </div>
    <div>
      <h4>商品説明　　</h4>
      <span><%= @item.explanation%></span>
    </div>
    <div>
      <h4>ジャンル　　</h4>
      <span><%= @item.genre.genre_name%></span>
    </div>
    <div>
      <h4>税込価格（税抜価格）　　</h4>
      <span><%= @item.price%>円</span>
    </div>
    <div>
      <h4>販売ステータス　　</h4>
      <span>
        <% if @item.is_status? %>
        販売中
        <% else %>
        売り切れ
        <% end %>
      </span>
    </div>
  </div>
  <div class="col-xs-2">
    <%= link_to "編集する", edit_admins_item_path, class: "btn btn-primary"
  </div>

</div>

app/views/admins/items/update.html.erb
<h1>Admins::Items#update</h1>
<p>Find me in app/views/admins/items/update.html.erb</p>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/homes/about.html.erb
<h1>About</h1>
<h2>ながのCakeは全国発送可能なケーキ屋さんです。<br>
お子様からお年寄りの方までお召し上がりいただけるよう、<br>
様々なバリエーションをご用意しております。<br>
また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
ぜひご注文ください。</h2>

app/views/homes/top.html.erb
<p>ようこそ、NaganoCakeへ！<br>
このサイトは、ケーキ販売のECサイトになります。<br>
会員でない方も商品の閲覧はできますが、<br>
購入には会員登録が必要になります。</p>
<div clsas="123">123
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nav navbar-left'>
        <h1>LOGO<h1>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
          
          
          
          
          
            <li>
              
              
              <%= link_to "商品一覧", "#", class: "glyphicon glyphicon-home home" %>
            
    </li>
            <li>
              
        <%= link_to "会員一覧", admins_customers_path, class: "glyphicon glyphicon-user users" %>
            </li>
            <li>
              
              
              
              
              <%= link_to "注文履歴一覧", "#", class: "glyphicon glyphicon-book books" %>
                                 </li>
        <li>
          
          
          
                          <%= link_to "ジャンル一覧", "#", class: "glyphicon glyphicon-log-out logout", method: :delete %>
      </li>
            <li>     
<%= link_to "ログアウト", destroy_admin_session_path, class: "glyphicon glyphicon-log-out logout", method: :delete %>
                 </li>
                     <% else %>
  <li class="header-right">
          
          
            <%= link_to "ログイン", new_admin_session_path %>
                    </li>
            <li class="header-right">
    <%= link_to "新規登録", new_admin_registration_path %>
                       </li>
         <li class="header-right">
               <%= link_to "商品一覧", "#" %>
          </li>
             <li class="header-right">
             <%= link_to "About", "#" %>
                      </li>

    <% end %>
        </ul>
            </nav>
    </div>
           </header>
    <br />
    <br />
    <br />
    <div class="container">
    <%= yield %>

  </body>
</html>